import Head from 'next/head'
import Image from 'next/image'
import Herosection from '../components/Herosection'
import Navbar from '../components/Navbar'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Online port betting at 1xBet | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     {/* Header */}
     <Navbar/>
     {/* Main section */}
     <main className='bg-[#1b4463] '>
      <Herosection/>
     </main>
    </div>
  )
}
